packages:
  - packages/*
catalog:
  "@arethetypeswrong/cli": ^0.17.1
  "@biomejs/biome": ^1.9.4
  "@changesets/cli": ^2.27.10
  "@total-typescript/tsconfig": ^1.0.4
  "@tsconfig/strictest": ^2.0.5
  "@types/debug": ^4.1.12
  "@types/node": ^22.10.2
  "@types/turndown": ^5.0.5
  automd: ^0.3.12
  citty: ^0.1.6
  consola: ^3.2.3
  cookie-es: ^1.2.2
  debug: ^4.4.0
  defu: ^6.1.4
  env-paths: ^3.0.0
  husky: ^9.1.7
  knip: ^5.40.0
  lint-staged: ^15.2.11
  ofetch: ^1.4.1
  pathe: ^1.1.2
  temporal-polyfill: ^0.2.5
  tsdoc-markdown: ^1.0.0
  turndown: ^7.2.0
  type-level-regexp: ^0.1.17
  typescript: ^5.7.2
  unbuild: ^3.0.1
  unplugin-purge-polyfills: ^0.0.7
  vitest: ^2.1.8
