packages:
  - packages/*
catalog:
  '@arethetypeswrong/cli': ^0.18.0
  '@biomejs/biome': ^1.9.4
  '@changesets/cli': ^2.27.12
  '@total-typescript/tsconfig': ^1.0.4
  '@tsconfig/strictest': ^2.0.5
  '@types/debug': ^4.1.12
  '@types/node': ^22.13.1
  '@types/turndown': ^5.0.5
  automd: ^0.4.0
  citty: ^0.1.6
  consola: ^3.4.0
  cookie-es: ^2.0.0
  debug: ^4.4.0
  defu: ^6.1.4
  env-paths: ^3.0.0
  husky: ^9.1.7
  knip: ^5.43.6
  lint-staged: ^15.4.3
  ofetch: ^1.4.1
  pathe: ^2.0.2
  temporal-polyfill: ^0.3.0
  tsdoc-markdown: ^1.1.1
  turndown: ^7.2.0
  type-level-regexp: ^0.1.17
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unplugin-purge-polyfills: ^0.1.0
  vitest: ^3.0.5
