packages:
  - packages/*
catalog:
  "@arethetypeswrong/cli": 0.17.0
  "@biomejs/biome": 1.9.4
  "@total-typescript/tsconfig": 1.0.4
  "@types/debug": 4.1.12
  "@types/node": 22.10.1
  citty: 0.1.6
  consola: 3.2.3
  debug: 4.4.0
  env-paths: 3.0.0
  pathe: 1.1.2
  rollup: 4.28.1
  unbuild: 2.0.0
  unplugin-purge-polyfills: 0.0.7
