name: CI

on: [push, pull_request]

permissions:
  # To fetch code (actions/checkout)
  contents: read

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.node-version }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at
        # https://nodejs.org/en/about/previous-releases
        node-version: [lts/*, latest]

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint
      - name: Knip
        run: pnpm run lint:knip
      - name: Build
        run: pnpm run build
      - name: Typecheck
        run: pnpm run typecheck
      - name: Test types
        run: pnpm run test:attw
