name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

permissions:
  # To fetch code (actions/checkout)
  contents: read

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.node-version }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at
        # https://nodejs.org/en/about/previous-releases
        node-version: [20, lts]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: true
      - name: Install dependencies
        run: vp install
      - name: Build
        run: vp run -r build
      - name: Check
        run: vp check
      - name: Test
        run: vp test
      - name: Test types
        run: vp run test:attw

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    uses: ./.github/workflows/release.yml # zizmor: ignore[self-repository] actionlint does not support $/ paths
