name: Release

on:
  workflow_call:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      # For softprops/action-gh-release to create GitHub release
      contents: write
    runs-on: ubuntu-latest
    environment: release
    strategy:
      matrix:
        # See supported Node.js release schedule at
        # https://nodejs.org/en/about/previous-releases
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: true
      - name: Install dependencies
        run: vp install
      - name: Creating .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@8488615a623b1b9c987934bb89eae8af6a946ac1 # v2.1.1
        with:
          publish-script: vp run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
