name: Release

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      # For softprops/action-gh-release to create GitHub release
      contents: write
    runs-on: ubuntu-latest
    environment: release
    strategy:
      matrix:
        # See supported Node.js release schedule at
        # https://nodejs.org/en/about/previous-releases
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: voidzero-dev/setup-vp@2dec1e33f4ab2c6d5bce1b0c4607961bb1a3f7a1 # v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: true
      - name: Install dependencies
        run: vp install
      - name: Creating .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: vp run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
